### ISSUE TITLE
Arduino GSM libraries

### ISSUE THREAD

**Issue by prudencer** [MakersTeam/Edison#2]
I can't seem to be able to use the GSM libraries on the Intel Edison board. I am using the SIM900 GSM module. It says GSM.h is does not run on the i686 architecture, how can I get around that problem?

**Comment by diego-villalobos** [comment]
The library is written based on the AVR architecture. The Edison module has a different architecture, that's the reason you get that error. You should try to port the entire library to be used on Edison or look for another library compatible with Edison. This question was asked in the Edison Community, please check the following thread: https://communities.intel.com/message/320790#320790.
